name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  # lint:
  #   name: â¬£ Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v4

  #     - uses: pnpm/action-setup@v3
  #       name: Install pnpm
  #       with:
  #         version: 9
  #         run_install: false

  #     - name: â” Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.10.0

  #     - name: ğŸ“¥ Install deps
  #       run: pnpm install

  #     - name: ğŸ”¬ Lint
  #       run: pnpm run lint

  # typecheck:
  #   name: Ê¦ Types
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v4

  #     - uses: pnpm/action-setup@v3
  #       name: Install pnpm
  #       with:
  #         version: 9
  #         run_install: false

  #     - name: â” Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.10.0

  #     - name: ğŸ“¥ Install deps
  #       run: pnpm install

  #     - name: ğŸ” Type check
  #       run: pnpm run typecheck

  # test:
  #   name: âš¡ Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v4

  #     - uses: pnpm/action-setup@v3
  #       name: Install pnpm
  #       with:
  #         version: 9
  #         run_install: false

  #     - name: â” Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.10.0

  #     - name: ğŸ“¥ Install deps
  #       run: pnpm install

  #     - name: âš¡ Run vitest
  #       run: pnpm run test

  publish:
    name: ğŸš€ Publish
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_SHA: ${{ github.sha }}
    # needs: [lint, typecheck, test]
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: ğŸ“¥ Install deps
        run: pnpm install

      - name: âš™ï¸ Build
        run: pnpm build

      - name: ğŸš€ Publish client
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            pnpm client run deploy:prod
          elif [[ "$GITHUB_REF_NAME" == "dev" ]]; then
            pnpm client run deploy:dev
          else
            echo "Not publishing client: this branch is not main or dev."
          fi

      - name: ğŸš€ Publish worker
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            pnpm worker run deploy:prod
          elif [[ "$GITHUB_REF_NAME" == "dev" ]]; then
            pnpm worker run deploy:dev
          else
            echo "Not publishing worker: this branch is not main or dev."
          fi
