name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  # lint:
  #   name: â¬£ Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v4

  #     - uses: pnpm/action-setup@v3
  #       name: Install pnpm
  #       with:
  #         version: 9
  #         run_install: false

  #     - name: â” Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.10.0

  #     - name: ğŸ“¥ Install deps
  #       run: pnpm install

  #     - name: ğŸ”¬ Lint
  #       run: pnpm run lint

  # typecheck:
  #   name: Ê¦ Types
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v4

  #     - uses: pnpm/action-setup@v3
  #       name: Install pnpm
  #       with:
  #         version: 9
  #         run_install: false

  #     - name: â” Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.10.0

  #     - name: ğŸ“¥ Install deps
  #       run: pnpm install

  #     - name: ğŸ” Type check
  #       run: pnpm run typecheck

  # test:
  #   name: âš¡ Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v4

  #     - uses: pnpm/action-setup@v3
  #       name: Install pnpm
  #       with:
  #         version: 9
  #         run_install: false

  #     - name: â” Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.10.0

  #     - name: ğŸ“¥ Install deps
  #       run: pnpm install

  #     - name: âš¡ Run vitest
  #       run: pnpm run test

  publish:
    name: ğŸš€ Publish
    runs-on: ubuntu-latest
    # needs: [lint, typecheck, test]
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: ğŸ“¥ Install deps
        run: pnpm install

      - name: âš™ï¸ Build
        run: pnpm build

      - name: ğŸš€ Publish to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          chmod +x ./.github/scripts/publish-client.sh
          ./.github/scripts/publish-client.sh

      - name: ğŸš€ Publish to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          chmod +x ./.github/scripts/publish-worker.sh
          ./.github/scripts/publish-worker.sh
