name: Stage Deployment

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Deploy target (client, server, or both)'
        required: true
        default: 'both'
        type: choice
        options:
          - client
          - server
          - both
  # Weird hack alert! We want to trigger stage deploys manually from feature
  # branches. Alas, GitHub will only allow workflow_dispatch on default branch.
  # To get around this we add `push:` to the workflow file, and push once to
  # get it to run. After it's run once, the GitHub CLI will be list it under
  # workflows, and we can run it manually. Once it shows up, remove `push:`
  # push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  deploy-client:
    name: ğŸš€ Deploy client to stage
    if: ${{ github.event.inputs.deployment_target == 'client' || github.event.inputs.deployment_target == 'both' }}
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: ğŸ“¥ Install deps
        run: pnpm install

      - name: âš™ï¸ Build
        run: pnpm build

      - name: ğŸš€ Deploy client to stage
        run: pnpm run client deploy:stage

  deploy-server:
    name: ğŸš€ Deploy server to stage
    if: ${{ github.event.inputs.deployment_target == 'server' || github.event.inputs.deployment_target == 'both' }}
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: ğŸ“¥ Install deps
        run: pnpm install

      - name: âš™ï¸ Build
        run: pnpm build

      - name: ğŸš€ Deploy server to stage
        run: pnpm run server deploy:stage
